version: '3.1'

services:
  pg:
    image: postgres:16.3
    #restart: always
    environment:
      POSTGRES_PASSWORD: partner
      POSTGRES_DB: partner_test
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


