version: '3.3'

services:
  buildfe:
    image: "harbor-test.7moor.com:8443/base/node:18.18"
    working_dir: "/home/data"
    # 安装依赖
#    entrypoint: "yarn"
    # 构建
    entrypoint: "yarn build"
    # 调试
    #entrypoint: "sleep 12345678s"
    volumes:
      - ./:/home/data
